# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Axepta-demo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Axepta-demo

  pod ‘Axepta’, :path => '../Axepta'

  target 'Axepta-demoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Axepta-demoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
